# Generated by Django 4.2.4 on 2023-09-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="img",
            field=models.ImageField(default="abc", upload_to="imgs"),
            preserve_default=False,
        ),
    ]
